name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
    - uses: actions/setup-node@v4.3.0
      with:
         node-version: '22.x'
    - name: use npm
      run: |
       npm install
       npm test